# Generated by Django 5.0 on 2023-12-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0002_article_image_alter_article_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default=None, upload_to='images/weblog/'),
        ),
    ]
