# Generated by Django 5.0 on 2024-01-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
