# Generated by Django 5.0 on 2024-01-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0010_author_category_article_author_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='garde',
            field=models.CharField(default=None, max_length=150, verbose_name='University education'),
            preserve_default=False,
        ),
    ]
