# Generated by Django 5.0 on 2024-01-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0011_author_garde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='garde',
            new_name='grade',
        ),
    ]
