# Generated by Django 5.0 on 2024-04-13 17:00

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('مشاوره آقایان', 'Men'), ('مشاوره زوجین', 'Couples'), ('مشاوره خانم ها', 'Women')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='static/images/teachers')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=150, verbose_name='University education')),
                ('intro', models.TextField(verbose_name='Teacher Introduction')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, auto_created=True, default=None, unique=True)),
                ('image', models.ImageField(default=None, upload_to='static/images/course')),
                ('title', models.CharField(max_length=120)),
                ('desc', models.TextField()),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='course.category')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='course.teacher')),
            ],
        ),
    ]
