# Generated by Django 5.0 on 2024-04-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('men', 'مشاوره آقایان'), ('couples', 'مشاوره زوجین'), ('women', 'مشاوره خانم ها')], max_length=50),
        ),
    ]
