# Generated by Django 5.0 on 2024-04-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Men', 'مشاوره آقایان'), ('Couples', 'مشاوره زوجین'), ('Women', 'مشاوره خانم ها')], max_length=50),
        ),
    ]
