# Generated by Django 5.0 on 2024-04-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fewdesc',
            field=models.TextField(default=None),
        ),
    ]
