# Generated by Django 5.0 on 2024-04-13 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_fewdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fewdesc',
        ),
    ]
