# Generated by Django 5.0 on 2024-04-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_fewdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fewdesc',
            field=models.TextField(default=None),
        ),
    ]
