# Generated by Django 5.0 on 2024-04-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
