# Generated by Django 5.0 on 2024-04-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_sessions_course_students_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='recommended',
            field=models.TextField(default=0),
        ),
    ]
