# Generated by Django 5.0 on 2024-04-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contact_created_contact_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
